server:
  port: 8084

spring:
  application:
    name: feed-service

  datasource:
    url: jdbc:mysql://mysql:3306/feed_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  # REDIS 
  data:
    redis:
      host: redis      
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 600000

  # RABBITMQ 
  rabbitmq:
    host: rabbitmq     
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

# FILE STORAGE 
file:
  upload-dir: uploads

# EUREKA 
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
  instance:
    prefer-ip-address: true   

# CLOUDINARY 
cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${API_KEY}
  api-secret: ${API_SECRET}

# Logging
logging:
  level:
    org.springframework.web: INFO